/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as GuestRouteImport } from './routes/guest'
import { Route as SitRouteImport } from './routes/sit'
import { Route as StudioRouteImport } from './routes/studio'
import { Route as ThesisRouteImport } from './routes/thesis'
import { Route as TrailerRouteImport } from './routes/trailer'
import { Route as EpisodesIndexRouteImport } from './routes/episodes/index'
import { Route as EpisodesSlugRouteImport } from './routes/episodes/$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const GuestRoute = GuestRouteImport.update({
  id: '/guest',
  path: '/guest',
  getParentRoute: () => rootRouteImport,
} as any)
const SitRoute = SitRouteImport.update({
  id: '/sit',
  path: '/sit',
  getParentRoute: () => rootRouteImport,
} as any)
const StudioRoute = StudioRouteImport.update({
  id: '/studio',
  path: '/studio',
  getParentRoute: () => rootRouteImport,
} as any)
const ThesisRoute = ThesisRouteImport.update({
  id: '/thesis',
  path: '/thesis',
  getParentRoute: () => rootRouteImport,
} as any)
const TrailerRoute = TrailerRouteImport.update({
  id: '/trailer',
  path: '/trailer',
  getParentRoute: () => rootRouteImport,
} as any)
const EpisodesIndexRoute = EpisodesIndexRouteImport.update({
  id: '/episodes/',
  path: '/episodes/',
  getParentRoute: () => rootRouteImport,
} as any)
const EpisodesSlugRoute = EpisodesSlugRouteImport.update({
  id: '/episodes/$slug',
  path: '/episodes/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/guest': typeof GuestRoute
  '/sit': typeof SitRoute
  '/studio': typeof StudioRoute
  '/thesis': typeof ThesisRoute
  '/trailer': typeof TrailerRoute
  '/episodes/$slug': typeof EpisodesSlugRoute
  '/episodes/': typeof EpisodesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/guest': typeof GuestRoute
  '/sit': typeof SitRoute
  '/studio': typeof StudioRoute
  '/thesis': typeof ThesisRoute
  '/trailer': typeof TrailerRoute
  '/episodes/$slug': typeof EpisodesSlugRoute
  '/episodes': typeof EpisodesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/guest': typeof GuestRoute
  '/sit': typeof SitRoute
  '/studio': typeof StudioRoute
  '/thesis': typeof ThesisRoute
  '/trailer': typeof TrailerRoute
  '/episodes/$slug': typeof EpisodesSlugRoute
  '/episodes/': typeof EpisodesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/guest'
    | '/sit'
    | '/studio'
    | '/thesis'
    | '/trailer'
    | '/episodes/$slug'
    | '/episodes/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/guest'
    | '/sit'
    | '/studio'
    | '/thesis'
    | '/trailer'
    | '/episodes/$slug'
    | '/episodes'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/guest'
    | '/sit'
    | '/studio'
    | '/thesis'
    | '/trailer'
    | '/episodes/$slug'
    | '/episodes/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  GuestRoute: typeof GuestRoute
  SitRoute: typeof SitRoute
  StudioRoute: typeof StudioRoute
  ThesisRoute: typeof ThesisRoute
  TrailerRoute: typeof TrailerRoute
  EpisodesSlugRoute: typeof EpisodesSlugRoute
  EpisodesIndexRoute: typeof EpisodesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guest': {
      id: '/guest'
      path: '/guest'
      fullPath: '/guest'
      preLoaderRoute: typeof GuestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sit': {
      id: '/sit'
      path: '/sit'
      fullPath: '/sit'
      preLoaderRoute: typeof SitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/studio': {
      id: '/studio'
      path: '/studio'
      fullPath: '/studio'
      preLoaderRoute: typeof StudioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/thesis': {
      id: '/thesis'
      path: '/thesis'
      fullPath: '/thesis'
      preLoaderRoute: typeof ThesisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trailer': {
      id: '/trailer'
      path: '/trailer'
      fullPath: '/trailer'
      preLoaderRoute: typeof TrailerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/episodes/': {
      id: '/episodes/'
      path: '/episodes'
      fullPath: '/episodes/'
      preLoaderRoute: typeof EpisodesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/episodes/$slug': {
      id: '/episodes/$slug'
      path: '/episodes/$slug'
      fullPath: '/episodes/$slug'
      preLoaderRoute: typeof EpisodesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  GuestRoute: GuestRoute,
  SitRoute: SitRoute,
  StudioRoute: StudioRoute,
  ThesisRoute: ThesisRoute,
  TrailerRoute: TrailerRoute,
  EpisodesSlugRoute: EpisodesSlugRoute,
  EpisodesIndexRoute: EpisodesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
